env:
    CONFIG: config.sh
    CIRRUS_SHELL: bash

task:
  name: "TWRP Recovery Build"
  timeout_in: 120m
  container:
      image: shazuxdubuntu/ubuntu:latest
      cpu: 8
      memory: 20G

  Sync_script:
      - curl -sL https://github.com/ShazuxD/TWRP_BUILDER_CI/raw/main/scripts/sync.sh | bash
  Build_script:
      - curl -sL https://github.com/ShazuxD/TWRP_BUILDER_CI/raw/main/scripts/build.sh | bash
  Upload_script:
      - curl -sL https://github.com/ShazuxD/TWRP_BUILDER_CI/raw/main/scripts/upload.sh | bash
